apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: black-tgb
  namespace: black-ns
spec:
  serviceRef:
    name: black-service
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:us-west-2:504968285206:targetgroup/lab-target-group-1/623d708aaf9e4303
