apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: argo-cd-tgb
  namespace: argocd
spec:
  serviceRef:
    name: argocd-server
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:504968285206:targetgroup/argo-cd-tg/d42c944cbe8a1142
